const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={apiUrl:'https://manpower-distribution-api.onrender.com',user:null,contractors:[],workers:[],projects:[],assignments:[],planning:[],reports:[],users:[],view:'planning',selectedId:null,month:new Date().toISOString().slice(0,7),busy:false};
const viewInfo={planning:['Planning','Plan required manpower and compare it with actual assignments.'],assignments:['Assignments','Who is working where and for what period.'],workers:['Workers','Employee list and contractor information.'],contractors:['Contractors','Companies used for manpower distribution.'],reports:['Weekly Reports','Saved weekly snapshots of active manpower.'],users:['Users & Access','Manage access to Manpower Distribution.']};
function api(p){return `${state.apiUrl}${p}`}
function esc(v){return v==null?'':String(v)}
function html(v){return esc(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showNotice(msg,error=false){const e=$('#notice');e.textContent=msg;e.classList.remove('hidden','notice-error');if(error)e.classList.add('notice-error');clearTimeout(showNotice.t);showNotice.t=setTimeout(()=>e.classList.add('hidden'),5000)}
function setBusy(on,title='Working…',text=''){state.busy=on;$('#busyOverlay').classList.toggle('hidden',!on);$('#busyTitle').textContent=title;$('#busyText').textContent=text}
async function request(path,options={}){const headers={...(options.headers||{})};if(options.body&&typeof options.body!=='string'){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body)}let r;try{r=await fetch(api(path),{...options,headers,credentials:'include'})}catch{throw new Error('Connection unavailable. Please try again.')}let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function landingReady(ready,msg=''){ $('#microsoftLoginBtn').disabled=!ready;$('#emergencyLoginBtn').disabled=!ready;$('#landingStatus').textContent=msg;$('#landingStatus').classList.remove('error')}
function authUi(){const logged=!!state.user;$('#loginLanding').classList.toggle('hidden',logged);$('#appShell').classList.toggle('hidden',!logged);$('#currentUser').textContent=logged?`${state.user.username} · ${state.user.accessLabel||''}`:'';$('#usersTab').classList.toggle('hidden',!state.user?.canManageUsers)}
async function restoreSession(){landingReady(false,'Connecting securely…');for(let i=0;i<12;i++){try{const r=await request('/api/auth/me');state.user=r.user;await loadAll();authUi();return}catch(e){if(!/Connection unavailable|502|503|504/.test(e.message)){state.user=null;authUi();landingReady(true,'');return}landingReady(false,i<2?'Starting secure server…':'Still starting secure server…');await wait(3000)}}landingReady(true,'Server is temporarily unavailable.');$('#landingStatus').classList.add('error')}
function cleanAuthParams(){const u=new URL(location.href);u.searchParams.delete('auth_code');u.searchParams.delete('auth_error');history.replaceState({},document.title,`${u.pathname}${u.search}${u.hash}`)}
async function completeMicrosoft(){const u=new URL(location.href),code=u.searchParams.get('auth_code'),err=u.searchParams.get('auth_error');if(!code&&!err)return false;cleanAuthParams();if(err){landingReady(true,err);$('#landingStatus').classList.add('error');return true}landingReady(false,'Completing Microsoft sign-in…');try{const r=await request('/api/auth/microsoft/exchange',{method:'POST',body:{code}});state.user=r.user;await loadAll();authUi()}catch(e){landingReady(true,e.message);$('#landingStatus').classList.add('error')}return true}
$('#microsoftLoginBtn').addEventListener('click',()=>{landingReady(false,'Opening Microsoft sign-in…');location.assign(api('/api/auth/microsoft/start'))});
$('#emergencyForm').addEventListener('submit',async e=>{e.preventDefault();if(state.busy)return;landingReady(false,'Signing in…');try{const r=await request('/api/auth/login',{method:'POST',body:{password:$('#emergencyPassword').value}});state.user=r.user;$('#emergencyPassword').value='';await loadAll();authUi()}catch(err){landingReady(true,err.message);$('#landingStatus').classList.add('error')}});
$('#logoutBtn').addEventListener('click',async()=>{try{await request('/api/auth/logout',{method:'POST'})}catch{}state.user=null;state.contractors=[];state.workers=[];state.projects=[];state.assignments=[];state.planning=[];authUi();landingReady(true,'')});
async function loadAll(){const b=await request('/api/bootstrap');state.user=b.user;state.contractors=b.contractors||[];state.workers=b.workers||[];state.projects=b.projects||[];state.assignments=b.assignments||[];state.planning=b.planning||[];state.reports=b.weeklySnapshots||[];render()}
function contractor(id,short=''){return state.contractors.find(x=>x.id===id)||state.contractors.find(x=>x.shortName===short)}
function project(id){return state.projects.find(x=>x.id===id)}
function worker(id){return state.workers.find(x=>x.id===id)}
function dateInAssignment(date,a){if(!a.startDate)return false;if(date<a.startDate)return false;if(a.endDate&&date>a.endDate)return false;return a.workStatus!=='leave'}
function factsFor(projectId,date){const rows=state.assignments.filter(a=>a.projectId===projectId&&dateInAssignment(date,a));const out={total:rows.length,Foreman:0,Fitter:0,Welder:0,'Pipe-fitter':0,Other:0};for(const a of rows){const t=/foreman/i.test(a.trade)?'Foreman':/pipe/i.test(a.trade)?'Pipe-fitter':/welder/i.test(a.trade)?'Welder':/fitter/i.test(a.trade)?'Fitter':'Other';out[t]=(out[t]||0)+1}return out}
function planCount(projectId,date,trade){return Number(state.planning.find(x=>x.projectId===projectId&&x.date===date&&x.trade===trade)?.count||0)}
function canEdit(){return state.user?.access==='edit_all'||state.user?.access==='edit'}
function metric(label,value){return `<div class="metric"><strong>${html(value)}</strong><span>${html(label)}</span></div>`}
function renderMetrics(){const active=state.assignments.filter(a=>a.overallStatus==='active').length;$('#metrics').innerHTML=metric('Workers',state.workers.length)+metric('Active assignments',active)+metric('Projects',state.projects.length)+metric('Contractors',state.contractors.length)}
function render(){if(!state.user)return;const [title,sub]=viewInfo[state.view];$('#viewTitle').textContent=title;$('#viewSubtitle').textContent=sub;renderMetrics();renderToolbar();if(state.view==='planning')renderPlanning();if(state.view==='assignments')renderAssignments();if(state.view==='workers')renderWorkers();if(state.view==='contractors')renderContractors();if(state.view==='reports')renderReports();if(state.view==='users')renderUsers()}
$$('.tab').forEach(b=>b.addEventListener('click',async()=>{if(b.dataset.view==='users'&&!state.user?.canManageUsers)return;state.view=b.dataset.view;state.selectedId=null;$$('.tab').forEach(x=>x.classList.toggle('active',x===b));if(state.view==='users')await loadUsers();render()}));
function renderToolbar(){const t=$('#toolbar');if(state.view==='planning'){t.innerHTML=`<div class="planning-controls"><button class="btn" id="prevMonth">←</button><input class="btn" id="monthInput" type="month" value="${state.month}"><button class="btn" id="nextMonth">→</button></div>${canEdit()?'<button class="btn btn-primary" id="addProjectBtn">+ Add project</button>':''}`;$('#monthInput').onchange=e=>{state.month=e.target.value;renderPlanning()};$('#prevMonth').onclick=()=>shiftMonth(-1);$('#nextMonth').onclick=()=>shiftMonth(1);$('#addProjectBtn')?.addEventListener('click',()=>editProject())}
else if(state.view==='assignments'){t.innerHTML=`${canEdit()?'<button class="btn btn-primary" id="addAssignmentBtn">+ Add assignment</button>':''}<input id="searchAssignments" class="btn" placeholder="Search worker or project…">`;$('#addAssignmentBtn')?.addEventListener('click',()=>editAssignment());$('#searchAssignments').oninput=renderAssignments}
else if(state.view==='workers'){t.innerHTML=`${canEdit()?'<button class="btn btn-primary" id="addWorkerBtn">+ Add worker</button>':''}<input id="searchWorkers" class="btn" placeholder="Search worker…">`;$('#addWorkerBtn')?.addEventListener('click',()=>editWorker());$('#searchWorkers').oninput=renderWorkers}
else if(state.view==='contractors'){t.innerHTML=canEdit()?'<button class="btn btn-primary" id="addContractorBtn">+ Add contractor</button>':'';$('#addContractorBtn')?.addEventListener('click',()=>editContractor())}
else if(state.view==='reports'){t.innerHTML=canEdit()?'<button class="btn btn-primary" id="saveSnapshotBtn">Save weekly snapshot</button>':'';$('#saveSnapshotBtn')?.addEventListener('click',saveSnapshot)}
else t.innerHTML=''}
function shiftMonth(delta){const [y,m]=state.month.split('-').map(Number);const d=new Date(y,m-1+delta,1);state.month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;render()}
function monthDates(){const [y,m]=state.month.split('-').map(Number),last=new Date(y,m,0).getDate();return Array.from({length:last},(_,i)=>`${y}-${String(m).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`)}
function renderPlanning(){const dates=monthDates(),trades=['Foreman','Fitter','Welder','Pipe-fitter'];let s='<div class="planning-grid"><table class="plan-table"><thead><tr><th class="sticky-col">Project / trade</th>'+dates.map(d=>`<th>${Number(d.slice(-2))}<br><small>${new Date(d+'T00:00:00').toLocaleDateString('en',{weekday:'short'})}</small></th>`).join('')+'</tr></thead><tbody>';for(const p of state.projects.filter(x=>x.active!==false)){s+=`<tr class="project-row"><td class="sticky-col">${html(p.name)}</td>${dates.map(d=>{const f=factsFor(p.id,d).total;const pl=trades.reduce((n,t)=>n+planCount(p.id,d,t),0);return `<td class="fact-cell ${f<pl?'short':'ok'}" title="Plan ${pl}, fact ${f}">${f}/${pl}</td>`}).join('')}</tr>`;for(const tr of trades){s+=`<tr><td class="sticky-col">↳ ${tr}</td>${dates.map(d=>{const f=factsFor(p.id,d)[tr]||0,pl=planCount(p.id,d,tr);return `<td>${canEdit()?`<input class="plan-input" data-project="${p.id}" data-date="${d}" data-trade="${tr}" value="${pl}" inputmode="numeric">`:`${pl}`}<div class="fact-cell ${f<pl?'short':'ok'}">${f}</div></td>`}).join('')}</tr>`}}s+='</tbody></table></div>';$('#content').innerHTML=s;$$('.plan-input').forEach(i=>i.addEventListener('change',savePlanCell))}
async function savePlanCell(e){const i=e.currentTarget,count=Math.max(0,Number(i.value)||0);try{await request('/api/planning',{method:'PUT',body:{projectId:i.dataset.project,date:i.dataset.date,trade:i.dataset.trade,count}});const old=state.planning.find(x=>x.projectId===i.dataset.project&&x.date===i.dataset.date&&x.trade===i.dataset.trade);if(old)old.count=count;else state.planning.push({projectId:i.dataset.project,date:i.dataset.date,trade:i.dataset.trade,count});renderPlanning()}catch(err){showNotice(err.message,true)}}
function table(headers,rows){return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function renderAssignments(){const q=($('#searchAssignments')?.value||'').toLowerCase();const rows=state.assignments.slice().sort((a,b)=>(b.startDate||'').localeCompare(a.startDate||'')).filter(a=>{const w=worker(a.workerId),p=project(a.projectId);return !q||`${w?.name||''} ${p?.name||''} ${a.trade||''}`.toLowerCase().includes(q)}).map(a=>{const w=worker(a.workerId),p=project(a.projectId),c=contractor(a.contractorId,a.contractorShort);return `<tr data-id="${a.id}"><td>${html(w?.name)}</td><td>${html(a.trade)}</td><td>${html(c?.shortName||a.contractorShort)}</td><td>${html(p?.name)}</td><td>${html(a.startDate)}</td><td>${html(a.endDate||'—')}</td><td><span class="badge ${a.workStatus==='leave'?'leave':'active'}">${a.workStatus==='leave'?'On leave':'Working'}</span></td><td>${html(a.overallStatus)}</td><td>${canEdit()?`<button class="btn edit-assignment" data-id="${a.id}">Edit</button>`:''}</td></tr>`});$('#content').innerHTML=table(['Worker','Trade','Company','Project','Start','End','Status','Overall',''],rows);$$('.edit-assignment').forEach(b=>b.onclick=()=>editAssignment(state.assignments.find(x=>x.id===b.dataset.id)))}
function renderWorkers(){const q=($('#searchWorkers')?.value||'').toLowerCase();const rows=state.workers.filter(w=>!q||`${w.name} ${w.trade} ${w.contractorShort}`.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name)).map(w=>{const c=contractor(w.contractorId,w.contractorShort);const active=state.assignments.filter(a=>a.workerId===w.id&&a.overallStatus==='active').map(a=>project(a.projectId)?.name).filter(Boolean).join(', ');return `<tr><td>${html(w.name)}</td><td>${html(w.trade)}</td><td>${html(c?.shortName||w.contractorShort)}</td><td>${html(active||'—')}</td><td>${canEdit()?`<button class="btn edit-worker" data-id="${w.id}">Edit</button>`:''}</td></tr>`});$('#content').innerHTML=table(['Worker','Trade','Company','Current project',''],rows);$$('.edit-worker').forEach(b=>b.onclick=()=>editWorker(state.workers.find(x=>x.id===b.dataset.id)))}
function renderContractors(){const rows=state.contractors.sort((a,b)=>a.name.localeCompare(b.name)).map(c=>{const count=state.workers.filter(w=>w.contractorId===c.id).length;return `<tr><td>${html(c.name)}</td><td>${html(c.shortName)}</td><td>${html(c.hourlyRate||'—')}</td><td>${count}</td><td>${canEdit()?`<button class="btn edit-contractor" data-id="${c.id}">Edit</button>`:''}</td></tr>`});$('#content').innerHTML=table(['Company','Short name','Hourly rate €','Workers',''],rows);$$('.edit-contractor').forEach(b=>b.onclick=()=>editContractor(state.contractors.find(x=>x.id===b.dataset.id)))}
function renderReports(){if(!state.reports.length){$('#content').innerHTML='<div class="empty">No weekly snapshots yet.</div>';return}$('#content').innerHTML=state.reports.slice().reverse().map(r=>`<div class="report-card"><div><strong>${html(r.label)}</strong><span>${html(r.createdAt)} · ${r.activeAssignments?.length||0} active assignments</span></div></div>`).join('')}
async function saveSnapshot(){setBusy(true,'Saving weekly snapshot…','Capturing the current active manpower.');try{await request('/api/reports/weekly-snapshot',{method:'POST'});await loadAll();showNotice('Weekly snapshot saved.')}catch(e){showNotice(e.message,true)}finally{setBusy(false)}}
async function loadUsers(){if(!state.user?.canManageUsers)return;try{state.users=(await request('/api/users')).users||[]}catch(e){showNotice(e.message,true)}}
function renderUsers(){const rows=state.users.map(u=>`<tr><td>${html(u.username)}</td><td>${html(u.entraUpn||'—')}</td><td>${html((u.roles||[]).join(', '))}</td></tr>`);$('#content').innerHTML=table(['Name','Microsoft account','Roles'],rows)}
function options(items,valueFn,labelFn,current=''){return items.map(x=>`<option value="${html(valueFn(x))}" ${valueFn(x)===current?'selected':''}>${html(labelFn(x))}</option>`).join('')}
function openEditor({title,eyebrow,fields,onSave}){$('#editorTitle').textContent=title;$('#editorEyebrow').textContent=eyebrow;$('#editorFields').innerHTML=fields;$('#editorError').classList.add('hidden');$('#editorForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());try{$('#editorSaveBtn').disabled=true;await onSave(data);$('#editorDialog').close();await loadAll();showNotice('Saved.')}catch(err){$('#editorError').textContent=err.message;$('#editorError').classList.remove('hidden')}finally{$('#editorSaveBtn').disabled=false}};$('#editorDialog').showModal()}
function f(label,name,value='',type='text',span=false){return `<label class="field ${span?'span-2':''}"><span>${label}</span><input name="${name}" type="${type}" value="${html(value)}"></label>`}
function sel(label,name,opts,span=false){return `<label class="field ${span?'span-2':''}"><span>${label}</span><select name="${name}">${opts}</select></label>`}
function editContractor(c={}){openEditor({title:c.id?'Edit contractor':'Add contractor',eyebrow:'CONTRACTOR',fields:f('Company name','name',c.name,'text',true)+f('Short name','shortName',c.shortName)+f('Hourly rate €','hourlyRate',c.hourlyRate,'number'),onSave:d=>request(c.id?`/api/contractors/${c.id}`:'/api/contractors',{method:c.id?'PUT':'POST',body:d})})}
function editWorker(w={}){openEditor({title:w.id?'Edit worker':'Add worker',eyebrow:'WORKER',fields:f('Name','name',w.name,'text',true)+f('Trade','trade',w.trade)+sel('Contractor','contractorId','<option value="">—</option>'+options(state.contractors,x=>x.id,x=>`${x.shortName} — ${x.name}`,w.contractorId)),onSave:d=>request(w.id?`/api/workers/${w.id}`:'/api/workers',{method:w.id?'PUT':'POST',body:d})})}
function editProject(p={}){openEditor({title:p.id?'Edit project':'Add project',eyebrow:'PROJECT',fields:f('Project name','name',p.name,'text',true),onSave:d=>request(p.id?`/api/projects/${p.id}`:'/api/projects',{method:p.id?'PUT':'POST',body:d})})}
function editAssignment(a={}){openEditor({title:a.id?'Edit assignment':'Add assignment',eyebrow:'ASSIGNMENT',fields:sel('Worker','workerId','<option value="">Select…</option>'+options(state.workers,x=>x.id,x=>x.name,a.workerId))+sel('Project','projectId','<option value="">Select…</option>'+options(state.projects,x=>x.id,x=>x.name,a.projectId))+f('Trade','trade',a.trade)+f('Start date','startDate',a.startDate,'date')+f('End date','endDate',a.endDate,'date')+sel('Work status','workStatus',`<option value="working" ${a.workStatus!=='leave'?'selected':''}>Working</option><option value="leave" ${a.workStatus==='leave'?'selected':''}>On leave</option>`),onSave:d=>request(a.id?`/api/assignments/${a.id}`:'/api/assignments',{method:a.id?'PUT':'POST',body:d})})}
$$('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog')?.close());
authUi();render();const handled=await completeMicrosoft();if(!handled)await restoreSession();
